<style>
    label{
        width:200px;
        display:inline-block;
        background:#efefef;
        padding:5px;
    }
    input{
        padding:5px;
    }
    .error{
        background:red;
        color:yellow;
        width:400px;
        padding:10px;
        margin-bottom:5px;
    }
</style>
<?php if(!empty($error)) : ?>
<div class="error">
    <?php echo $error; ?>
</div>
<?php endif; ?>
<form method="post">
    <div>
        <label for="name">Nome completo:</label>
        <input type="text" id="name" name="name" value="<?php echo $name??''; ?>">
    </div>
    <div>
        <label for="userName">Nome de login:</label>
        <input type="text" id="userName" name="userName" value="<?php echo $userName??''; ?>">
    </div>
    <div>
        <label for="zipCode">CEP</label>
        <input type="text" id="zipCode" name="zipCode" value="<?php echo $zipCode??''; ?>">
    </div>
    <div>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" value="<?php echo $email??''; ?>">
    </div>
    <div>
        <label for="password">Senha (8 caracteres mínimo, contendo pelo menos 1 letra
            e 1 número):</label>
        <input type="password" id="password" name="password" value="<?php echo $password??'' ?>">
    </div>
    <input type="submit" value="Cadastrar">
</form>
